#!/bin/sh
action="$2"
case "$action" in
  up)
        if [ -f /etc/reboot ]
        then
                rm -f /etc/reboot
                exec /etc/init.d/on.sh &
        else
                touch /etc/reboot
                dmesg | tail -n 10 > /etc/dmesg
                /sbin/reboot
        fi
    ;;
  down)
     exec /etc/init.d/off.sh &
     ;;
esac
